package scrpts;

public interface infoClass {
    String[] bookTitles = {
            "1984", "To Kill a Mockingbird", "The Great Gatsby", "Pride and Prejudice", "The Catcher in the Rye",
            "Animal Farm", "Lord of the Flies", "Jane Eyre", "Wuthering Heights", "Little Women",
            "Great Expectations", "The Grapes of Wrath", "Catch-22", "Beloved", "Mrs. Dalloway",
            "Frankenstein", "Dracula", "The Picture of Dorian Gray", "Brave New World", "Fahrenheit 451",
            "The Old Man and the Sea", "Of Mice and Men", "A Tale of Two Cities", "Crime and Punishment", "The Brothers Karamazov",
            "Anna Karenina", "War and Peace", "Les Misérables", "The Count of Monte Cristo", "Don Quixote",
            "Moby-Dick", "The Scarlet Letter", "The Odyssey", "The Iliad", "The Divine Comedy",
            "Heart of Darkness", "Ulysses", "One Hundred Years of Solitude", "Things Fall Apart", "The Stranger",
            "The Metamorphosis", "The Bell Jar", "Slaughterhouse-Five", "A Clockwork Orange", "Invisible Man",
            "Native Son", "East of Eden", "The Sun Also Rises", "On the Road", "Lolita",
            "The Hobbit", "The Fellowship of the Ring", "The Two Towers", "The Return of the King", "Harry Potter and the Sorcerer's Stone",
            "Harry Potter and the Chamber of Secrets", "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Goblet of Fire", "Harry Potter and the Order of the Phoenix", "Harry Potter and the Half-Blood Prince",
            "Harry Potter and the Deathly Hallows", "A Game of Thrones", "A Clash of Kings", "A Storm of Swords", "A Feast for Crows",
            "A Dance with Dragons", "The Name of the Wind", "The Wise Man's Fear", "The Way of Kings", "Words of Radiance",
            "Oathbringer", "Rhythm of War", "Mistborn: The Final Empire", "The Well of Ascension", "The Hero of Ages",
            "Dune", "Dune Messiah", "Children of Dune", "Ender's Game", "Speaker for the Dead",
            "Foundation", "Foundation and Empire", "Second Foundation", "Neuromancer", "Snow Crash",
            "Hyperion", "The Fall of Hyperion", "The Left Hand of Darkness", "A Wizard of Earthsea", "The Dispossessed",
            "American Gods", "Good Omens", "Stardust", "Coraline", "The Graveyard Book",
            "Neverwhere", "The Ocean at the End of the Lane", "The Fifth Season", "The Obelisk Gate", "The Stone Sky",
            "The Girl with the Dragon Tattoo", "The Girl Who Played with Fire", "The Girl Who Kicked the Hornet's Nest", "Gone Girl", "The Girl on the Train",
            "Big Little Lies", "Sharp Objects", "Dark Places", "The Da Vinci Code", "Angels & Demons",
            "The Lost Symbol", "Inferno", "Origin", "The Silence of the Lambs", "Red Dragon",
            "Hannibal", "The Godfather", "The Maltese Falcon", "The Big Sleep", "And Then There Were None",
            "Murder on the Orient Express", "Death on the Nile", "The ABC Murders", "The Murder of Roger Ackroyd", "Rebecca",
            "In Cold Blood", "Midnight in the Garden of Good and Evil", "The Woman in the Window", "Before I Go to Sleep", "The Silent Patient",
            "Thinking, Fast and Slow", "Outliers", "The Tipping Point", "Blink", "David and Goliath",
            "Sapiens: A Brief History of Humankind", "Homo Deus", "21 Lessons for the 21st Century", "Educated", "The Glass Castle",
            "Wild", "Eat, Pray, Love", "Bossypants", "Becoming", "A Promised Land",
            "Steve Jobs", "Elon Musk", "The Diary of a Young Girl", "Night", "Man's Search for Meaning",
            "The Hunger Games", "Catching Fire", "Mockingjay", "The Ballad of Songbirds and Snakes", "Divergent",
            "Insurgent", "Allegiant", "The Maze Runner", "The Scorch Trials", "The Death Cure",
            "Percy Jackson: The Lightning Thief", "The Sea of Monsters", "The Titan's Curse", "The Battle of the Labyrinth", "The Last Olympian",
            "Twilight", "New Moon", "Eclipse", "Breaking Dawn", "The Fault in Our Stars",
            "Looking for Alaska", "Paper Towns", "An Abundance of Katherines", "Turtles All the Way Down", "The Giver",
            "Number the Stars", "Holes", "Bridge to Terabithia", "Charlotte's Web", "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
            "Prince Caspian", "The Voyage of the Dawn Treader", "The Silver Chair", "The Horse and His Boy", "The Magician's Nephew",
            "The Last Battle", "Matilda", "Charlie and the Chocolate Factory", "James and the Giant Peach", "The BFG",
            "Wonder", "The Perks of Being a Wallflower", "Speak", "Thirteen Reasons Why", "Simon vs. the Homo Sapiens Agenda",
            "Ready Player One", "Ready Player Two", "The Golden Compass", "The Subtle Knife", "The Amber Spyglass",
            "The Book Thief", "All the Light We Cannot See", "The Nightingale", "The Kite Runner", "A Thousand Splendid Suns",
            "And the Mountains Echoed", "Life of Pi", "The Help", "Water for Elephants", "Memoirs of a Geisha",
            "The Color Purple", "The Secret Life of Bees", "Where the Crawdads Sing", "Little Fires Everywhere", "Everything I Never Told You",
            "Crazy Rich Asians", "China Rich Girlfriend", "Rich People Problems", "The Joy Luck Club", "Interpreter of Maladies",
            "White Teeth", "On Beauty", "Swing Time", "Normal People", "Conversations with Friends",
            "Beautiful World, Where Are You", "The Seven Husbands of Evelyn Hugo", "Daisy Jones & The Six", "Malibu Rising", "Carrie Soto Is Back",
            "Circe", "The Song of Achilles", "Atonement", "Never Let Me Go", "The Remains of the Day",
            "Cloud Atlas", "Middlesex", "The Virgin Suicides", "Room", "The Lovely Bones",
            "Eleanor Oliphant Is Completely Fine", "A Man Called Ove", "Beartown", "Us Against You", "Anxious People",
            "My Brilliant Friend", "The Story of a New Name", "Those Who Leave and Those Who Stay", "The Story of the Lost Child", "Pachinko",
            "It", "The Shining", "Doctor Sleep", "Pet Sematary", "Misery",
            "Carrie", "Salem's Lot", "The Stand", "Under the Dome", "11/22/63",
            "Bird Box", "World War Z", "The Haunting of Hill House", "We Have Always Lived in the Castle", "House of Leaves",
            "Mexican Gothic", "The Only Good Indians", "The Exorcist", "Rosemary's Baby", "Something Wicked This Way Comes",
            "Let the Right One In", "Interview with the Vampire", "The Vampire Lestat", "The Queen of the Damned", "Ring",
            "A Brief History of Time", "The Selfish Gene", "Cosmos", "The Grand Design", "Astrophysics for People in a Hurry",
            "Guns, Germs, and Steel", "Collapse", "The God Delusion", "Meditation", "The Republic",
            "Beyond Good and Evil", "Thus Spoke Zarathustra", "The Prince", "The Art of War", "Tao Te Ching",
            "Critique of Pure Reason", "Being and Time", "The Stranger", "Nausea", "Ethics",
            "Sophie's World", "Freakonomics", "Superfreakonomics", "Nudge", "Predictably Irrational",
            "Watchmen", "V for Vendetta", "Batman: The Killing Joke", "Batman: Year One", "The Dark Knight Returns",
            "Sandman: Preludes & Nocturnes", "Sandman: The Doll's House", "Maus", "Persepolis", "Fun Home",
            "Saga", "Y: The Last Man", "Paper Girls", "Locke & Key", "Preacher",
            "Hellboy", "Sin City", "Scott Pilgrim's Precious Little Life", "Blankets", "Ghost World",
            "Akira", "Naruto", "One Piece", "Dragon Ball", "Death Note"
    };
    String[] humanNames = {
            "Adam", "Sophia", "James", "Olivia", "Ethan", "Emma", "Liam", "Ava", "Mason", "Charlotte",
            "Noah", "Amelia", "Lucas", "Isabella", "Logan", "Mia", "Elijah", "Harper", "Oliver", "Evelyn",
            "Henry", "Abigail", "Alexander", "Emily", "Sebastian", "Ella", "Benjamin", "Scarlett", "Jackson", "Grace",
            "Samuel", "Luna", "Owen", "Chloe", "Caleb", "Layla", "Nathan", "Ellie", "Gabriel", "Zoey",
            "Wyatt", "Sophie", "Ryan", "Madison", "Daniel", "Violet", "Matthew", "Aria", "David", "Hazel",
            "Joseph", "Aurora", "Lucas", "Savannah", "Jack", "Lily", "Carter", "Brooklyn", "Julian", "Hannah",
            "Levi", "Penelope", "Isaac", "Riley", "Thomas", "Lillian", "Andrew", "Paisley", "Dylan", "Nora",
            "Luke", "Skylar", "Hunter", "Elliana", "Jonathan", "Caroline", "Levi", "Eva", "Colton", "Victoria",
            "Aaron", "Naomi", "Christian", "Aubrey", "Evan", "Kennedy", "Miles", "Mackenzie", "Isaiah", "Alyssa",
            "Landon", "Autumn", "Connor", "Piper", "Elias", "Stella", "Isaiah", "Zoe", "Gavin", "Alexa",
            "Adrian", "Ruby", "Angel", "Claire", "Asher", "Sadie", "Dominic", "Lyla", "Elliot", "Willow",
            "Julian", "Delilah", "Carson", "Isla", "Austin", "Ariana", "Brody", "Mila", "Ian", "Alice",
            "Vincent", "Elena", "Axel", "Taylor", "Jason", "Hadley", "Justin", "Madeline", "Maxwell", "Sarah",
            "Jace", "Brielle", "Nolan", "Ashley", "Roman", "Adeline", "Harrison", "Melody", "Ashton", "Katherine",
            "Bryce", "Morgan", "Micah", "Emery", "Tristan", "Peyton", "Ryder", "Jordyn", "Declan", "Quinn",
            "Holden", "Reese", "Silas", "Reagan", "Miles", "Valeria", "Malachi", "Leilani", "Rafael", "Amara",
            "Bennett", "Ariel", "Zion", "Lila", "Everett", "Brooklynn", "Sawyer", "Isabel", "Parker", "Eliana",
            "Maddox", "Camila", "Calvin", "Vivian", "Braxton", "Ivy", "Zander", "Genevieve", "Hayes", "Juliette",
            "Kaden", "Rose", "Chance", "Rebecca", "Grant", "Faith", "Knox", "Eloise", "Collin", "Madilyn",
            "Tucker", "Athena", "Victor", "Lilah", "Alec", "June", "Wesley", "Esther", "Joel", "Summer",
            "Blaine", "Sienna", "Reid", "Lacey", "Erik", "Cecilia", "Bryan", "Esme", "Simon", "Annie",
            "Felix", "Clara", "Griffin", "Leona", "Shawn", "Arden", "Quincy", "Aurelia", "Porter", "Matilda",
            "Clark", "Sylvia", "Dean", "Iris", "Elliott", "Margot", "Graham", "Carmen", "Finn", "Noelle",
            "Jared", "Celeste", "Chase", "Nadia", "Cooper", "Amelie", "Cade", "Phoebe", "Blake", "Daphne",
            "Reese", "Raelyn", "Easton", "Lorelai", "Bryant", "Athalia", "Pierce", "Juliana", "Drew", "Fiona"
    };
    String[] bookGenres = {
            "Science Fiction", "Fantasy", "Mystery", "Thriller", "Romance", "Horror", "Historical Fiction", "Biography",
            "Autobiography", "Memoir", "Self-Help", "Health & Wellness", "Travel", "True Crime", "Poetry", "Graphic Novel",
            "Young Adult", "Dystopian", "Classic", "Adventure"
    };
}
